### ISSUE TITLE
Support tracking the C include stack

### ISSUE THREAD

**Issue by eternaleye** [visq/language-c#12]
As I found and posted on https://github.com/jameysharp/corrode/issues/50 :

> gcc -E puts these directives into the output:
> 
> ``` C
> # linenum filename flags
> ```
> 
> The (space-separated) flags are:
> 1. Begin a new file
> 2. Return to a file after an included file ends
> 3. Came from a system header file
> 4. Should be considered to be wrapped in `extern "C"` (irrelevant for Corrode, as it lacks C++)
> 
> As a result, you can simply treat "1" as "push" (with "3" setting a flag on it), "2" as "pop", and any directive with neither replaces the top-of-stack - that gives you the full include stack.
> 
> Then, at each newline that does not end such a directive, increment the line number of the current top of the stack.
> 
> EDIT: Oh, hm. Looks like `Language.C` mishandles this - fixing it would require altering `Language.C.Data.Position` to have a `posParent` or `posCause` member, which is itself a `Maybe Position`, so as to form the include stack, and then track it that way.

**Comment by visq** [comment]
First, for reference, https://gcc.gnu.org/onlinedocs/cpp/Preprocessor-Output.html.
Language.C currently does not keep the include stack, but it does not mishandle flags; they are simply 
ignored.
I think the include stack is a great addition to the language C parser, and implemented it today. However, before merging into master, space usage needs to be observed, because there was a history of space leaks in the Lexer.

**Comment by visq** [comment]
Memory usage seems to be slightly up but ok in the position_stack branch:

master: 10203Mb cummulative parse_dg
position_stack: 10222Mb cummulative parse_dg

So I'll merge this change for 0.7.0

**Comment by visq** [comment]
I reduced the memory usage for tracking the include stack, rearraning the Position datatype.
There is a lot of variance in memory usage (?!), so this time I reran the parse_dg suite 30 times for each configuration.

master: 10199 +- 0.7444681
position_stack_new: 10205 +- 0.27
position_stack_old: 10220 +- 3.034097
