### ISSUE TITLE
Hackage release and major version bump

### ISSUE THREAD

**Issue by acowley** [visq/language-c#13]
Hi, I need `language-c > 0.5` for `c2hs` to work for me, so I'd like a new hackage release as it's been a while. The latest changes, however, will necessitate a major version bump as they break `c2hs` in a minor way (the type of `partitionDeclSpecs`). The `c2hs` fix is trivial, but we can't PR that until `language-c-0.6.0` goes up on hackage.

**Comment by visq** [comment]
Hi Anthony,
sure, I'll prepare a release as soon as possible,   probably this evening.
Best, benedikt

Anthony Cowley <notifications@github.com> schrieb am Mo., 8. Aug. 2016,
18:16:
