### ISSUE TITLE
Benign duplicate type definition is not an error in GNU C

### ISSUE THREAD

**Issue by iphydf** [visq/language-c#14]
``` c
typedef int Foo;
typedef int Foo;
```

This code compiles fine with gcc. It is a GNU extension. `GNU99` mode does not (but should) support it. It is a real problem, because OSX headers define `va_list` twice: once in `/usr/include/sys/_types/_va_list.h` and once in `$TOOLCHAIN/usr/lib/clang/7.3.0/include/stdarg.h`. They both define it to `__builtin_va_list`.

**Comment by lambdageek** [comment]
This is also going to be required for C11 support.  C11 § 6.7 ¶3 says:

> a typedef name may be redefined to denote the same type as it currently does, provided that type is not a variably modified type

I'm not sure if "same type" has a formal definition somewhere in the standard, but this notion of equivlance isn't in `language-c` yet.

I suppose `sameType` might mean given a pair of `Type`s:
1. if either input is a `TypeDefs`, resolve it and recurse
2. if it's a `TypeName` compare that everything is identical
3. if it's an `ArrayType`, or `PtrType` check that the base type is `sameType` and the qualifiers are identical (and array size for arrays is ???)
4. if it's a `FunctionType` check that the return and arg types (but not param identifiers?) are the same type and same variadicity.  (and neither function type is incomplete?)

(By "identical" I mean the finest equivalence ignoring NodeInfo and attributes)
