### ISSUE TITLE
Version parsing in Clang availability attribute

### ISSUE THREAD

**Issue by evincarofautumn** [visq/language-c#19]
I encountered this in the OS X 10.12 SDK (`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/string.h`):

```
__OSX_AVAILABLE(10.12.1)
// expands to
__OS_AVAILABILITY(macosx,introduced=10.12.1)
// expands to
__attribute__((availability(macosx,introduced=10.12.1)))
```

`language-c` tries to parse the version number as a float, leading to a syntax error:

```
The symbol `.1' does not fit here.
```

This is an unfortunate complication, but I guess it should be supported.

**Comment by visq** [comment]
I think there is no proper specification of OS X extensions to the C language, right?
Anyway, support for OS X is certainly worthwile, happy to merge patches.
In this case, we would need to extend the lexer (new token), the parser, the AST, the pretty printer etc.; not difficult, but requires some effort.
