### ISSUE TITLE
Possible __asm__ syntax with trailing colon in parameters

### ISSUE THREAD

**Issue by mtolly** [visq/language-c#83]
I ran into a `c2hs` issue when compiling [`fltkhs`](https://github.com/deech/fltkhs) on Windows with OpenGL support, and I think I've traced it to the syntax issue it is complaining about. Please let me know if this should instead be reported somewhere else.

The error I got complained of this header in my Stack GHC folder:

```
C:/Users/Mike/AppData/Local/Programs/stack/x86_64-windows/ghc-8.8.4/mingw/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:836: (column 222) [ERROR]  >>> Syntax error !
  The symbol `)' does not fit here.
```

The contents of the header are more or less this (line numbers differ somewhat but all the pieces below are the same): https://github.com/Alexpux/mingw-w64/blob/2dce559/mingw-w64-headers/include/psdk_inc/intrin-impl.h

As best as I can tell, what's happening is that:

1. [`__FLAGCLOBBER2` is being defined to nothing](https://github.com/Alexpux/mingw-w64/blob/2dce559/mingw-w64-headers/include/psdk_inc/intrin-impl.h#L86)

2. [This macro](https://github.com/Alexpux/mingw-w64/blob/2dce559/mingw-w64-headers/include/psdk_inc/intrin-impl.h#L251-L259) and [this macro](https://github.com/Alexpux/mingw-w64/blob/2dce559/mingw-w64-headers/include/psdk_inc/intrin-impl.h#L271-L279) have `__asm__` statements that end in `: __FLAGCLOBBER2);`, which becomes `: );`

3. The macros are then used a few places including [here](https://github.com/Alexpux/mingw-w64/blob/2dce559/mingw-w64-headers/include/psdk_inc/intrin-impl.h#L763) (which is the line 836 in my version)

So, it looks like either [here](https://github.com/visq/language-c/blob/c307dee/src/Language/C/Parser/Parser.y#L526-L530) or [here](https://github.com/visq/language-c/blob/c307dee/src/Language/C/Parser/Parser.y#L555-L558) in `Parser.y` could be modified to accept the `: )` sequence with a colon but no clobbers. But, I am not sure if it would be correct to do so. If this all looks sensible I can whip up a PR.

Also pinging @deech due to the `fltkhs` build issue. (Can be worked around for now by editing the header.)

**Comment by expipiplus1** [comment]
I'd be happy to merge such a change if that syntax is accepted by gcc or clang.

A test or two to make sure that the change doesn't interfere with existing asm parsing would be good, but not required (the test suite is a little unwieldy!)

Otherwise it might be possible to define `__FLAGCLOBBER2` to be `: foo` or `` and omit the last `:`, or perhaps there's an "empty" clobber which could be used here?
