### ISSUE TITLE
Support for _Float16

### ISSUE THREAD

**Issue by Archaversine** [visq/language-c#98]
I see that #52 adds support for `_Float{32, 64, 128}` which all seem to work, but there seems to be no support for `_Float16`. Is this something that can be added in?

**Comment by vmchale** [comment]
I've encountered something maybe related:

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:614: (column 17) [ERROR]  >>> Syntax error !
  The symbol `__fabsf16' does not fit here.
```

**Comment by gwright83** [comment]
Earlier today I tested building a large project on macos 14.7.1/Xcode 16.1 using c2hs patched with jcmartin's update.  It previously failed with the `__fabsf16 does not fit here` error; now it builds properly.

This seems to resolve the problem introduced (at least) by Apple's support of 16 bit floats in math.h.
